---
services:
  juice:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    restart: always
  zap:
    image: jverhoelen/owasp-zap-with-entrypoint
    user: zap
    ports:
      - "8080:8080"
    restart: always
version: "3.3"
