version: "3.7"

services:
  juice:
    image: bkimminich/juice-shop:latest
    container_name: juice
    ports:
      - "3000:3000"
    restart: always
  zap:
    image: jverhoelen/owasp-zap-with-entrypoint
    container_name: zap
    user: zap
    ports:
      - "8080:8080"
    restart: always
