name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04

    services:
      zap:
        image: jverhoelen/owasp-zap-with-entrypoint
        ports:
          - 8080:8080

    steps:
      - name: configure ZAP to exclude hosts of no interest
        run: curl "http://localhost:8080/JSON/core/action/excludeFromProxy/?regex=%5E.*%28google%7Cgstatic%7Cherokucdn%7Cgetmdl%7Ccloudflare%7Ccypress%29.*"
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Run Cypress proxied by ZAP
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          headless: true
        env:
          HTTP_PROXY: http://localhost:8080
          HTTPS_PROXY: http://localhost:8080
      - name: run OWASP ZAP active scan
        if: always()
        run: |
          curl 'http://localhost:8080/JSON/ascan/action/scan/?url=https%3A%2F%2Fjuice-shop.herokuapp.com%2F&recurse=true&inScopeOnly=false&scanPolicyName=&method=&postData=&contextId='
          sleep 120
      - name: download ZAP report
        if: always()
        run: sleep 20 && curl "http://localhost:8080/OTHER/core/other/htmlreport/" > zap-report.html
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ZAP-report
          path: zap-report.html
