name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04

    services:
      zap:
        image: jverhoelen/owasp-zap-with-entrypoint
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config-file: cypress-heroku.json
          env: HTTP_PROXY=http://localhost:8080,HTTP_PROXY=http://localhost:8080
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: download ZAP report
        run: curl "http://localhost:8080/OTHER/core/other/htmlreport/"
