name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04

    services:
      owasp-juiceshop:
        image: bkimminich/juice-shop
        ports:
        - 3000:3000

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config-file: cypress.json