name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04

    services:
      juiceshop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
      zap:
        image: jverhoelen/owasp-zap-with-entrypoint
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config-file: cypress-local.json
          env: HTTP_PROXY=http://localhost:8080
      - uses: wei/curl@master
        with:
          args: http://localhost:8080/OTHER/core/other/jsonreport/
